### ISSUE TITLE
Error using vim-lsc with pyls

### ISSUE THREAD

**Issue by softinio** [natebosch/vim-lsc#128]
I got this:

```
[lsc:Error] StdErr from pyls: 2018-12-19 18:16:13,185 UTC - ERROR - jsonrpc.endpoint - Failed to handle request 645^@Traceback (most recent call last):^@  File "/usr/loca
l/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 113, in consume^@    self._handle_request(message['id'], message['method'], message.get('params'))^@  File "/usr/
local/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 182, in _handle_request^@    handler_result = handler(params)^@  File "/usr/local/lib/python3.7/site-packages
/jsonrpc/dispatchers.py", line 23, in handler^@    return method(**(params or {}))^@  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 264, in m_text
_document__document_highlight^@    return self.highlight(textDocument['uri'], position)^@  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 208, in h
ighlight^@    return flatten(self._hook('pyls_document_highlight', doc_uri, position=position)) or None^@  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py"
, line 118, in _hook^@    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)^@  File "/usr/local/lib/python3.7/site-packages/plugg
y/hooks.py", line 284, in __call__^@    return self._hookexec(self, self.get_hookimpls(), kwargs)^@  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line
 67, in _hookexec^@    return self._inner_hookexec(hook, methods, kwargs)^@  File "/usr/local/lib/python3.7/site-packages/pluggy/_tracing.py", line 80, in __call__^@    r
eturn outcome.get_result()^@  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result^@    raise ex[1].with_traceback(ex[2])^@  File "/usr
/local/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call^@    result = func()^@  File "/usr/local/lib/python3.7/site-packages/pluggy/_tracing.py", lin
e 78, in <lambda>^@    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))^@  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", lin
e 61, in <lambda>^@    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,^@  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208
, in _multicall^@    return outcome.get_result()^@  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result^@    raise ex[1].with_tracebac
k(ex[2])^@  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall^@    res = hook_impl.function(*args)^@  File "/usr/local/lib/python3.
7/site-packages/pyls/plugins/highlight.py", line 10, in pyls_document_highlight^@    usages = document.jedi_script(position).usages()^@  File "/usr/local/lib/python3.7/si
te-packages/pyls/workspace.py", line 214, in jedi_script^@    return jedi.Script(**kwargs)^@  File "/usr/local/lib/python3.7/site-packages/jedi/api/__init__.py", line 118
, in __init__^@    cache_path=settings.cache_directory,^@  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 388, in parse_and_get_code^@    r
eturn self.grammar.parse(code=code, path=path, **kwargs), code^@  File "/usr/local/lib/python3.7/site-packages/parso/grammar.py", line 76, in parse^@    return self._pars
e(code=code, **kwargs)^@  File "/usr/local/lib/python3.7/site-packages/parso/grammar.py", line 126, in _parse^@    new_lines=lines^@  File "/usr/local/lib/python3.7/site-
packages/parso/python/diff.py", line 152, in update^@    self._copy_from_old_parser(line_offset, i2, j2)^@  File "/usr/local/lib/python3.7/site-packages/parso/python/diff
.py", line 211, in _copy_from_old_parser^@    from_ = copied_nodes[0].get_start_pos_of_prefix()[0] + line_offset^@  File "/usr/local/lib/python3.7/site-packages/parso/tre
e.py", line 264, in get_start_pos_of_prefix^@    return self.children[0].get_start_pos_of_prefix()^@  File "/usr/local/lib/python3.7/site-packages/parso/python/tree.py",
line 125, in get_start_pos_of_prefix^@    previous_leaf = self.get_previous_leaf()^@  File "/usr/local/lib/python3.7/site-packages/parso/tree.py", line 74, in get_previou
s_leaf^@    i = c.index(node)^@ValueError: <Function: generate_obscured_filename_from_conversation@31-46> is not in list^@
```

Any ideas?

**Comment by olafurpg** [comment]
@softinio have you tried enabling the `suppress_stderr` option?

**Comment by natebosch** [comment]
It looks like a bug in the server, have you filed an issue on the pyls repo?

Here is the output without the vim newline translation:

```
2018-12-19 18:16:13,185 UTC - ERROR - jsonrpc.endpoint - Failed to handle request 645
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/local/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/local/lib/python3.7/site-packages/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 264, in m_text_document__document_highlight
    return self.highlight(textDocument['uri'], position)
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 208, in highlight
    return flatten(self._hook('pyls_document_highlight', doc_uri, position=position)) or None
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 118, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/_tracing.py", line 80, in __call__
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/usr/local/lib/python3.7/site-packages/pluggy/_tracing.py", line 78, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/site-packages/pyls/plugins/highlight.py", line 10, in pyls_document_highlight
    usages = document.jedi_script(position).usages()
  File "/usr/local/lib/python3.7/site-packages/pyls/workspace.py", line 214, in jedi_script
    return jedi.Script(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/jedi/api/__init__.py", line 118, in __init__
    cache_path=settings.cache_directory,
  File "/usr/local/lib/python3.7/site-packages/jedi/evaluate/__init__.py", line 388, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code
  File "/usr/local/lib/python3.7/site-packages/parso/grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/parso/grammar.py", line 126, in _parse
    new_lines=lines
  File "/usr/local/lib/python3.7/site-packages/parso/python/diff.py", line 152, in update
    self._copy_from_old_parser(line_offset, i2, j2)
  File "/usr/local/lib/python3.7/site-packages/parso/python/diff.py", line 211, in _copy_from_old_parser
    from_ = copied_nodes[0].get_start_pos_of_prefix()[0] + line_offset
  File "/usr/local/lib/python3.7/site-packages/parso/tree.py", line 264, in get_start_pos_of_prefix
    return self.children[0].get_start_pos_of_prefix()
  File "/usr/local/lib/python3.7/site-packages/parso/python/tree.py",line 125, in get_start_pos_of_prefix
    previous_leaf = self.get_previous_leaf()
  File "/usr/local/lib/python3.7/site-packages/parso/tree.py", line 74, in get_previous_leaf
    i = c.index(node)
ValueError: <Function: generate_obscured_filename_from_conversation@31-46> is not in list
```

**Comment by natebosch** [comment]
Closing since it looks like this is likely a bug in the server - ideally it shouldn't be dumping a stack trace to stderr.

As mentioned you can also hide this if the server is otherwise behaving normally. See `:help lsc-server-suppress_stderr`

**Comment by natebosch** [comment]
I just noticed I had a pretty significant protocol bug, fixed in https://github.com/natebosch/vim-lsc/commit/c64ef9e4aeb96b2a226124e1a920d81538fe0340

I don't know if that bug is at all related to this error. Let me know if you're hitting this consistently and believe it's a client bug and not a server bug.
