### ISSUE TITLE
Unable to Startup Microsoft's Python-Language-Server

### ISSUE THREAD

**Issue by ryanp97** [natebosch/vim-lsc#163]
I've built a release executable of the python-language-server from master, but the server is unable to start with vim-lsc. The executable was built with the following command: `dotnet publish -c Release --runtime osx-x64`

Here's a minimal vimrc that shows the error:
```
call plug#begin('~/.vim/plugged')

" Autocomplete
Plug 'maralla/completor.vim'
Plug 'natebosch/vim-lsc'

call plug#end()


"""""""""""""""""""" Completor Settings """"""""""""""""""""
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"

nnoremap <silent> K :call completor#do('doc')<cr>
autocmd InsertLeave * pclose " Close doc preview buffer on InsertLeave
let g:completor_completion_delay = 0
let g:completor_def_split = 'vsplit'
let g:completor_auto_close_doc = 0
let g:completor_python_binary = '/usr/local/bin/python3'
let g:completor_gocode_binary = $HOME . '/Go/bin/gocode'

" let g:lsc_server_commands = {'python': 'pyls'}
let g:lsc_server_commands = {'python': $HOME . '/logscript'}
let g:lsc_trace_level = 'verbose'

let g:lsc_enable_autocomplete = v:false
let g:lsc_reference_highlights = v:false
let g:lsc_auto_map = {
    \ 'GoToDefinitionSplit': ['<C-W>]', '<C-W><C-]>'],
    \ 'FindReferences': 'gr',
    \ 'FindImplementations': 'gI',
    \ 'Rename': 'R',
    \ 'ShowHover': v:false,
    \ 'Completion': 'completefunc',
    \}
```

where the contents of the logscript are: `tee /tmp/in.log | path/to/repo/output/bin/Release/Microsoft.Python.LanguageServer.LanguageServer | tee /tmp/out.log`

*in.log*
```
Content-Length: 555

{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///Users/ryan/Drive/School/cse_homework/447/hw2","capabilities":{"workspace":{"applyEdit":true},"textDocument":{"completion":{"completionItem":{"snippetSupport":false}},"synchronization":{"willSaveWaitUntil":false,"willSave":false,"didSave":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","source"]}}},"signatureHelp":{"dynamicRegistration":false},"definition":{"dynamicRegistration":false}}},"processId":43412,"trace":"verbose"}}
```

*out.log*
```
Content-Length: 693

{"jsonrpc":"2.0","method":"telemetry/event","params":{"EventName":"python_language_server/rpc.exception","Properties":{"name":"NullReferenceException","stackTrace":"   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/Implementation/Server.cs:line 105\n   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/LanguageServer.Lifetime.cs:line 36","method":"initialize","plsVersion":"1.0.0.0"},"Measurements":{}}}Content-Length: 585

{"jsonrpc":"2.0","error":{"code":-32000,"message":"Object reference not set to an instance of an object.","data":"   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/Implementation/Server.cs:line 105\n   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/LanguageServer.Lifetime.cs:line 36"},"id":1}
```

**Comment by natebosch** [comment]
Looks like a bug in the server.

Here is the error:
```
Object reference not set to an instance of an object.
   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/Implementation/Server.cs:line 105
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/LanguageServer.Lifetime.cs:line 36
```

That line takes me to:
https://github.com/Microsoft/python-language-server/blob/d63a6463fb14144e390ace912f42faaeb372fc48/src/LanguageServer/Impl/Implementation/Server.cs#L105-L107

I don't know C# well, however it looks like maybe they are unconditionally trying to read `initializationOptions.displayOptions` even though `initializationOptions` is allowed to be null, and it is by default in this client.

I'd recommend filing a bug on that repo and pointing out that `initializationOptions` is optional any may be omitted in the request.

If you want to work around this bug in the server for now you could try one of the following:

```viml
let g:lsc_server_commands = {
    \ 'python': {
    \   'name': 'python-language-server',
    \   'command': $HOME . '/logscript',
    \   'message_hooks': {
    \     'initialize': {
    \       'initializationOptions': {}
    \    }
    \}
```

or it might need

```viml
let g:lsc_server_commands = {
    \ 'python': {
    \   'name': 'python-language-server',
    \   'command': $HOME . '/logscript',
    \   'message_hooks': {
    \     'initialize': {
    \       'initializationOptions': {'displayOptions': v:null}
    \    }
    \}
```

**Comment by ryanp97** [comment]
I'll go ahead and submit an issue over there. As for the work-arounds you suggested, both of them resulted in this output:
```
Content-Length: 917

{"jsonrpc":"2.0","method":"telemetry/event","params":{"EventName":"python_language_server/rpc.exception","Properties":{"name":"NullReferenceException","stackTrace":"   at Microsoft.Python.Analysis.Core.Interpreter.InterpreterConfiguration..ctor(IReadOnlyDictionary`2 properties) in /Users/ryan/python-language-server/src/Analysis/Core/Impl/Interpreter/InterpreterConfiguration.cs:line 58\n   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/Implementation/Server.cs:line 119\n   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/LanguageServer.Lifetime.cs:line 36","method":"initialize","plsVersion":"1.0.0.0"},"Measurements":{}}}Content-Length: 809

{"jsonrpc":"2.0","error":{"code":-32000,"message":"Object reference not set to an instance of an object.","data":"   at Microsoft.Python.Analysis.Core.Interpreter.InterpreterConfiguration..ctor(IReadOnlyDictionary`2 properties) in /Users/ryan/python-language-server/src/Analysis/Core/Impl/Interpreter/InterpreterConfiguration.cs:line 58\n   at Microsoft.Python.LanguageServer.Implementation.Server.InitializeAsync(InitializeParams params, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/Implementation/Server.cs:line 119\n   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationToken cancellationToken) in /Users/ryan/python-language-server/src/LanguageServer/Impl/LanguageServer.Lifetime.cs:line 36"},"id":1}
```
Now it seems errors will occur [here](https://github.com/Microsoft/python-language-server/blob/d63a6463fb14144e390ace912f42faaeb372fc48/src/LanguageServer/Impl/Implementation/Server.cs#L119) based on the interpreter specified in the initialization options.

**Comment by ryanp97** [comment]
Filed the issue with the language-server repo. It seems that entire method is unconditionally accessing initializationOptions.

**Comment by natebosch** [comment]
From the response it look like you'll need a non-empty and non-null `displayOptions` value. Hopefully the documentation for the server points out what you need. You'll want to configure it for now in the same way I've shown above:

```viml
let g:lsc_server_commands = {
    \ 'python': {
    \   'name': 'python-language-server',
    \   'command': $HOME . '/logscript',
    \   'message_hooks': {
    \     'initialize': {
    \       'initializationOptions': {'displayOptions': {
    \         'whateverKeysAreRequired': 'whatever values are required',
    \        }
    \      }
    \    }
    \}
```

You may want to subscribe to updates on https://github.com/natebosch/vim-lsc/issues/132 - when I find the time to implement that these settings will hopefully be easier to manage.

**Comment by ryanp97** [comment]
It seems that the server wasn't written to comply with `initializeOptions` being `null` and it won't be fixed for a while unfortunately. Thanks for the help anyways!
